# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Development - Rule 21
email: dwightaspencer@gmail.com
description: >
Full Stack Solutions architect
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dwightaspencer.com" # the base hostname & protocol for your site
twitter_username: denzuko
github_username:  denzuko

# Build settings
markdown: kramdown
source: src
destination: public
sass:
  sass_dir: assets/css/modules
  style: compressed
  
permalink: /:categories/:title/

# live reload
livereload: true
reload_port: 5678

# gems
gems:
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-sitemap

# plugin settings
autoprefixer:
  browsers:
  - last 2 versions

exclude: ['node_modules', 'webpack', 'Gemfile', 'Gemfile.lock', 'Rakefile']